public class daftarProduk {
    //Membuat class daftarProduk yang berupa linkedList untuk menyimpan produk yang ada di toko
    public static linkedList list=new linkedList();
    public static linkedList listedProduct(){
        produk kitkat=new produk(1,"kitkat",5000);
        produk kopiko=new produk(3,"kopiko",500);
        produk Indomie=new produk(6,"Indomie",2500);
        produk Popmie=new produk(2,"Pop Mie",5000);
        produk Oreo=new produk(4,"Oreo",2000);
        produk bimoli=new produk(5,"Bimoli",25000);
        produk Saos=new produk(7, "Saos", 5000);
        produk Kecap=new produk(8, "Kecap", 5000);
        produk Kopi=new produk(9, "Kopi", 5000);
        produk shampo=new produk(10,"shampo",7000);
        produk batrai=new produk(11,"batrai",6000);
        produk rokok=new produk(12,"rokok",12000);
        produk SabunMandi=new produk(13, "Sabun Mandi", 3000);
        produk PastaGigi=new produk(14, "Pasta Gigi", 4000);
        produk SikatGigi=new produk(15, "Sikat Gigi", 3000);
        produk MinyakGoreng=new produk(16, "Minyak Goreng", 10000);
        produk Susu=new produk(17, "Susu", 8000);
        produk Teh=new produk(18, "Teh", 5000);
        produk Tissue=new produk(19, "Tissue", 5000);
        produk Roti=new produk(20, "Roti", 6000);
        produk Pampers=new produk(21, "Pampers", 10000);
        produk Parfum=new produk(22, "Parfum", 15000);
        produk BukuGambar=new produk(23,"Buku Gambar",17500);
        produk Gula=new produk(24, "Gula", 5000);
        produk Garam=new produk(25, "Garam", 5000);
        produk IceCream=new produk(26, "Ice Cream", 7000);
        produk Buah=new produk(27, "Buah", 8000);
        produk AirMineral=new produk(28, "Air Mineral", 4000);
        produk Sapu=new produk(29, "Sapu", 6000);
        produk Sayur=new produk(30, "Sayuran", 8000);
        produk Pensil=new produk(31, "Pensil", 4000);
        produk Penghapus=new produk(32, "Penghapus", 3000);
        produk Spidol=new produk(33, "Spidol", 5000);
        produk Penggaris=new produk(34, "Penggaris", 3000);
        produk Jangka=new produk(35, "Jangka", 7000);
        produk Pulpen=new produk(36, "Pulpen", 3000);
        produk Kuas=new produk(37, "Kuas", 5000);

        list.add(kitkat);
        list.add(kopiko);
        list.add(Indomie);
        list.add(Popmie);
        list.add(Oreo);
        list.add(bimoli);
        list.add(Spidol);
        list.add(Penggaris);
        list.add(shampo);
        list.add(SikatGigi);
        list.add(Kecap);
        list.add(Kuas);
        list.add(AirMineral);
        list.add(Pampers);
        list.add(Jangka);
        list.add(PastaGigi);
        list.add(Penghapus);
        list.add(SabunMandi);
        list.add(Saos);
        list.add(Sapu);
        list.add(Sayur);
        list.add(Susu);
        list.add(Buah);
        list.add(Pensil);
        list.add(Parfum);
        list.add(Jangka);
        list.add(Pulpen);
        list.add(Kuas);
        list.add(Kopi);
        list.add(batrai);
        list.add(rokok);
        list.add(MinyakGoreng);
        list.add(Teh);
        list.add(Tissue);
        list.add(Roti);
        list.add(Gula);
        list.add(Garam);
        list.add(IceCream);
        list.add(BukuGambar);

        return list;
    }
}
